from django.urls import path
from articles.views.article import (
    FilterLinksAPIView,
    RecommendedArticlesListAPIView,
    BreakingArticlesListAPIView,
    ArticleDetailAPIView,
    CreateArticleAPIView,
    UpdateArticleAPIView,
    UploadImageForArticleAPIView,
    DeleteArticleAPIView,
    ToggleArticleLikeAPIView,
    ToggleArticleSavedAPIView,
    TrackArticleReadAPIView,
    CreateSaveDirectoryAPIView,
    SaveDirectoriesListAPIView,
    SavedArticlesListAPIView,
    CheckArticleSavedAPIView,
    DeleteSaveDirectoryAPIView,
    UpdateSaveDirectoryAPIView,
    MorningArticlesAPIView,
    AfternoonArticlesAPIView,
    NightArticlesAPIView
)

urlpatterns = [
    path('filter-links/', FilterLinksAPIView.as_view(), name='filter_links'),
    path('get-recommended-articles/', RecommendedArticlesListAPIView.as_view(), name='get_articles'),
    path('get-breaking-articles/', BreakingArticlesListAPIView.as_view(), name='get_articles'),
    path('detail/<str:article_id>/', ArticleDetailAPIView.as_view(), name='get_article_detail'),
    path('create/', CreateArticleAPIView.as_view(), name='create_article'),
    path('update/<str:article_id>/', UpdateArticleAPIView.as_view(), name='update_article'),
    path('upload-image/', UploadImageForArticleAPIView.as_view(), name='upload_image_for_article'),
    path('delete/<str:article_id>/', DeleteArticleAPIView.as_view(), name='delete_article'),
    path('like/<str:article_id>/', ToggleArticleLikeAPIView.as_view(), name='toggle_article_like'),
    path('save/<str:article_id>/', ToggleArticleSavedAPIView.as_view(), name='toggle_article_saved'),
    path('track-read/', TrackArticleReadAPIView.as_view(), name='track_article_read'),
    path('save-directories/', SaveDirectoriesListAPIView.as_view(), name='get_save_directories'),
    path('create-save-directory/', CreateSaveDirectoryAPIView.as_view(), name='create_save_directory'),
    path('delete-save-directory/<str:directory_id>/', DeleteSaveDirectoryAPIView.as_view(), name='delete_save_directory'),
    path('update-save-directory/<str:directory_id>/', UpdateSaveDirectoryAPIView.as_view(), name='update_save_directory'),
    path('saved/', SavedArticlesListAPIView.as_view(), name='get_saved_articles'),
    path('get-morning-articles/', MorningArticlesAPIView.as_view(), name='morning_articles'),
    path('get-afternoon-articles/', AfternoonArticlesAPIView.as_view(), name='afternoon_articles'),
    path('get-night-articles/', NightArticlesAPIView.as_view(), name='night_articles'),
    path('check-save/<str:article_id>/', CheckArticleSavedAPIView.as_view(), name='check_article_saved'),
]