# Generated by Django 5.2.1 on 2025-05-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_caver',
            field=models.ImageField(blank=True, null=True, upload_to='profile_cover/', verbose_name='profile cover'),
        ),
    ]
